AWSTemplateFormatVersion: '2010-09-09'
Description: ECR repository for API.

Parameters:
  Name:
    Type: String
    Default: ecscicd

Resources:
  # ECR
  EcrRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Sub ${Name}-repo
      ImageScanningConfiguration:
        ScanOnPush: true
      Tags:
        - Key: Name
          Value: !Sub ${Name}-repo

Outputs:
  EcrRepositoryUri:
    Value: !GetAtt EcrRepository.RepositoryUri
    Export:
      Name: !Sub ${Name}-ecr-repo-uri
