AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFront distribution for backend-alb and frontend-s3

Parameters:
  Name:
    Type: String
    Default: ecscicd
  AcmCertificateArn:
    Type: String
  CustomDomainName:
    Type: String
  Route53HostZoneId:
    Type: String

Resources:
  # Origin access control for S3 bucket
  FrontendOriginAccessControl:
    Type: AWS::CloudFront::OriginAccessControl
    Properties:
      OriginAccessControlConfig:
        Name: !Sub ${Name}-frontend-oac
        OriginAccessControlOriginType: s3
        SigningBehavior: no-override
        SigningProtocol: sigv4

  # CloudFront distribution for frontend
  FrontendDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        Aliases:
        - !Ref CustomDomainName
        DefaultRootObject: index.html
        Origins:
        - Id: S3Origin
          DomainName:
            Fn::ImportValue: !Sub ${Name}-frontend-bucket-dnsname
          OriginAccessControlId: !GetAtt FrontendOriginAccessControl.Id
          S3OriginConfig: {}
        - Id: AlbEcsApi
          DomainName:
            Fn::ImportValue: !Sub ${Name}-alb-dns-name
          CustomOriginConfig:
            HTTPPort: 80
            OriginProtocolPolicy:  http-only
        DefaultCacheBehavior:
          TargetOriginId: S3Origin
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods:
            - GET
            - HEAD
            - OPTIONS
          CachedMethods:
            - GET
            - HEAD
            - OPTIONS
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: none
          Compress: true
        CacheBehaviors:
          - PathPattern: '/api/*'
            TargetOriginId: AlbEcsApi
            ViewerProtocolPolicy: redirect-to-https
            ForwardedValues:
              QueryString: false
              Cookies:
                Forward: none
        CustomErrorResponses:
          - ErrorCachingMinTTL: 300
            ErrorCode: 403
            ResponseCode: 200
            ResponsePagePath: /index.html
          - ErrorCachingMinTTL: 300
            ErrorCode: 404
            ResponseCode: 200
            ResponsePagePath: /index.html
        ViewerCertificate:
          AcmCertificateArn: !Ref AcmCertificateArn
          SslSupportMethod: sni-only
          MinimumProtocolVersion: TLSv1.2_2021
        HttpVersion: http2and3
        PriceClass: PriceClass_200
      Tags:
        - Key: Name
          Value: !Sub ${Name}-cloudfront

  # Bucket policy for S3 bucket
  FrontendBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket:
        Fn::ImportValue: !Sub ${Name}-frontend-bucket-name
      PolicyDocument:
        Statement:
        - Sid: AllowCloudFrontServicePrincipal
          Effect: Allow
          Principal:
            Service: cloudfront.amazonaws.com
          Action: s3:GetObject
          Resource:
            Fn::Join:
              - ''
              - - 'arn:aws:s3:::'
                - Fn::ImportValue: !Sub ${Name}-frontend-bucket-name
                - '/*'
          Condition:
            StringEquals:
              'AWS:SourceArn': !Sub arn:aws:cloudfront::${AWS::AccountId}:distribution/${FrontendDistribution}

  # Route53 A Record for Custom Domain
  CustomDomainARecord:
    Type: AWS::Route53::RecordSet
    Properties:
      Type: A
      Name: !Ref CustomDomainName
      AliasTarget:
        DNSName: !GetAtt FrontendDistribution.DomainName
        HostedZoneId: Z2FDTNDATAQYW2
      HostedZoneId: !Ref Route53HostZoneId

Outputs:
  CloudFrontDistributionId:
    Value: !GetAtt FrontendDistribution.Id
    Export:
      Name: !Sub "${Name}-cloudfront-distribution-id"